### ISSUE TITLE
Weird WHERE / ORDER BY issue

### ISSUE THREAD

**Issue by richmarr** [dsferruzza/simpleSqlParser#17]
I'm using the V2 branch, and seeing this response from sql2ast:

```
{ status: false, index: 43, expected: /IN/i }
```

My query is below. If I remove the `where` clause, or the `order by` clause it parses just fine.

```
select foobar from foo where bar = 7 order by foobar
```

I'm still not completely familiar with the source though so it's not clear to me what's causing the error. I assume it's talking about `/IN/i` because it's the last operator it tries in the list and that one of the patterns involved is leaking slightly? Not sure. Will keep looking, if you have any ideas where to focus I'd be glad to hear them

**Comment by dsferruzza** [comment]
There was a big bug indeed.
Let me know if it is not completely solved.

Thanks for reporting!
