### ISSUE TITLE
columnName contains 'set', return wrong ast

### ISSUE THREAD

**Issue by iammapping** [dsferruzza/simpleSqlParser#2]
Hi,
   It's a simple and great lib of sql parser. But I found one bug:
if column name contains 'set' (I think other keywords would be the same), the parsed ast object will have an item of 'SET', It's unexpected.
e.g.

```
var ast = simpleSqlParser.sql2ast('select setup, abcd from test');
console.log(ast);
// { SELECT: [], SET: [ 'up', 'abcd' ], FROM: [ { table: 'test', as: '' } ] }
```

**Comment by dsferruzza** [comment]
You are right, the following test fails:

``` js
deepEqual(m.sql2ast('SELECT column1, setup, column2 FROM table'), {
    'SELECT': [{name: 'column1'}, {name: 'setup'}, {name: 'column2'}],
    'FROM': [{
        table: 'table',
        as: '',
    }],
});
```

I will try to fix it, maybe in a few hours.

Thanks for your report!

**Comment by dsferruzza** [comment]
Now it should works fine!
