### ISSUE TITLE
how to use node install v2

### ISSUE THREAD

**Issue by binlaniua** [dsferruzza/simpleSqlParser#20]
how to use node install v2

**Comment by dsferruzza** [comment]
Hi!

I'm not sure what your question is, but I will take it as _"how can I install v2 via npm?"_.

Currently v2 is not available through npm.
But if it helps you, I can tag an alpha version and publish it so you can install it using npm.

Is this what you meant?

**Comment by binlaniua** [comment]
yes, i want install v2 use npm to install
thanks for you reply

**Comment by dsferruzza** [comment]
Sorry for the delay; I just pushed a `2.0.0-alpha.1` version on npm!
