### ISSUE TITLE
simpleSqlParser.withoutDeps.js doesn't seem to work out of the box

### ISSUE THREAD

**Issue by reatkin2** [dsferruzza/simpleSqlParser#21]
simpleSqlParser.withoutDeps.js:159 Uncaught TypeError: Cannot read property 'seq' of undefined

Parsimmon is null

**Comment by dsferruzza** [comment]
Hi!

Could you send the HTML file you used to get this error, please?

**Comment by reatkin2** [comment]
I got it by just switching demo.html to use withoutDeps.

**Comment by dsferruzza** [comment]
Well that's normal: the difference between `simpleSqlParser.js` and `simpleSqlParser.withoutDeps.js` is that the second does **not** include [Parsimmon](https://github.com/jneen/parsimmon/) (the parser combinator lib simpleSqlParser uses). This can be useful when your app/page already includes Parsimmon and you don't want to load it twice.

So if you use `simpleSqlParser.withoutDeps.js`, you need to ensure that the Parsimmon lib is loaded in the global variable `Parsimmon`. In mosts cases you will want to use `simpleSqlParser.js` (or the minified version).

**Comment by reatkin2** [comment]
Yep, sorry.  Had switched them up in my head.

**Comment by dsferruzza** [comment]
No problem
