### ISSUE TITLE
Ignores minus sign

### ISSUE THREAD

**Issue by anvog** [dsferruzza/simpleSqlParser#25]
This sql statment `"DELETE FROM table WHERE id = -5;"` delivers the result 

> Object { operator="=",  left="id",  right="5"}

but right should be "-5".

Tested with commit 4e16a4d.

**Comment by dsferruzza** [comment]
Hi!

When I run `DELETE FROM table WHERE id = -5` with 4e16a4d6fb3270c6f610cc0006d02636581a2ca4 on the `v2` branch, I get this AST:

``` json
{
    "status": true,
    "value": {
        "type": "delete",
        "from": [
            {
                "table": "table",
                "alias": null,
                "expression": "table",
                "position": {
                    "start": 12,
                    "end": 17
                }
            }
        ],
        "where": {
            "expression": "id = -5",
            "position": {
                "start": 24,
                "end": 31
            }
        }
    }
}
```

Have you tried the `v2` branch?

**Comment by anvog** [comment]
Hi thanks for the fast response.

No I used v1.

EDIT: I tested it with v2 and it works fine.

**Comment by dsferruzza** [comment]
Nice :)
