### ISSUE TITLE
JOIN without correct condition throws error

### ISSUE THREAD

**Issue by oshamin** [dsferruzza/simpleSqlParser#9]
There is error in JOIN condition parsing
Following SQL query :
SELECT name, address FROM Student JOIN Transcript Student.sid=Transcript.sid
without ON produces error on parsing empty condition.

I can create fix, but do not know what is better.
Either create AST["JOIN"] with empty condition or just ignore such JOIN's.

**Comment by oshamin** [comment]
I thought about my question, and for me it looks like creation AST["JOIN"] with empty condition is better option.
Waiting for your answer.

**Comment by dsferruzza** [comment]
If I summarize, you think this test should pass?

``` js
q = 'SELECT * FROM table LEFT JOIN table2 t2 table.id = t2.id_table';
        deepEqual(m.sql2ast(q), {
            'SELECT': [{name: '*'}],
            'FROM': [{
                table: 'table',
                as: '',
            }],
            'JOIN': [
                {
                    type: 'left',
                    table: 'table2', // NOT 'table2 table.id = t2.id_table'
                    as: 't2',
                    cond: '',
                },
            ],
        }, q);
```

Is this a valid SQL query?

Yes, we could avoid the parser to crash in this case.
But because of its bad conception, it would append the condition `Student.sid=Transcript.sid` in the `table` or the `alias` field (_see the comment in my example_).
A simple fix would be to say that the table/alias can't have spaces, but it is not a good idea, because it is possible to have something like `LEFT JOIN `my table``, right?

How would you fix it?

**Comment by oshamin** [comment]
Such query is not valid, because there is no condition ON.

``` sql
SELECT * FROM table LEFT JOIN table2 AS t2 table.id = t2.id_table
```

But at least the parser should not end up with error.

``` javascript
Uncaught TypeError: Cannot read property '0' of undefined simpleSqlParser.js:368
```

I think there are two ways:
1. Ignore invalid Joins
2. Ignore invalid Joins conditions

In my opinion, second choice is better. We build partially AST.
It would be enough to produce following AST structure:

``` javascript
q = 'SELECT * FROM table LEFT JOIN table2 AS t2 table.id = t2.id_table';
        deepEqual(m.sql2ast(q), {
            'SELECT': [{name: '*'}],
            'FROM': [{
                table: 'table',
                as: '',
            }],
            'JOIN': [
                {
                    type: 'left',
                    table: 'table2',
                    as: 't2 table.id = t2.id_table',
                    cond: '',
                },
            ],
        }, q);
```

What do you think?

**Comment by dsferruzza** [comment]
This make sense.
So you think we should consider that it is OK if it outputs `as: 't2 table.id = t2.id_table'` in that case?

**Comment by oshamin** [comment]
Yes, it is ok.
I do not see other options to handle this issue.

**Comment by dsferruzza** [comment]
I made a fix.
Does it look good to you?

**Comment by oshamin** [comment]
Yes, thank you for the fix
